# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 11:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kobocat_domain', models.CharField(max_length=200)),
                ('koboform_domain', models.CharField(max_length=200)),
                ('enketo_server_domain', models.CharField(max_length=200)),
                ('enketo_web_domain', models.CharField(max_length=200)),
                ('kobocat_port', models.CharField(max_length=200)),
                ('koboform_port', models.CharField(max_length=200)),
                ('enketo_server_port', models.CharField(max_length=200)),
                ('enketo_web_port', models.CharField(max_length=200)),
                ('src_directory', models.CharField(max_length=200)),
                ('kobocat_socket', models.CharField(max_length=200)),
                ('koboform_socket', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
