# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='socket_status',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
