# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_file_socket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='db_password',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='db_server_ip',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='db_user',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AddField(
            model_name='file',
            name='virtualenv',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='enketo_server_domain',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='enketo_server_port',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='enketo_web_domain',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='enketo_web_port',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='kobocat_domain',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='kobocat_port',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='kobocat_socket',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='koboform_domain',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='koboform_port',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='koboform_socket',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='socket_status',
            field=models.CharField(blank='true', max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='src_directory',
            field=models.CharField(blank='true', max_length=200),
        ),
    ]
