# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170409_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('category', models.CharField(blank=True, max_length=250)),
                ('value', models.DecimalField(decimal_places=3, max_digits=20)),
            ],
        ),
    ]
